# Project information
site_name: PPO_ROS
site_url: https://team-re-boot/ppo_ros/
site_author: Masaya Kataoka
site_description: ''
copyright: Copyright &copy; 2025 - Team Re-boot

# Repository
repo_name: team-re-boot/ppo_ros
repo_url: https://github.com/team-re-boot/ppo_ros
edit_uri: ''
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/icon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

extra_css:
  - https://use.fontawesome.com/releases/v5.15.0/css/all.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorials:
    - Setup: tutorial/setup.md
    - Go2 Walk: tutorial/go2_walk.md
